Raise exception when combineCards tries to combine datacards with regularization terms
refer to discussion here: https://hypernews.cern.ch/HyperNews/CMS/get/higgs-combination/1661/1.html

When combining one or more datacards, a regularization term that looks like the following

constr0 constr @3*(@0-2*@1+@2) r_0,r_1,r_2,regularize[0.] delta[10.]

triggers this kind of exception:

Traceback (most recent call last):
  File "/work/gallim/CMSSW/CMSSW_11_2_0_pre10/bin/slc7_amd64_gcc900/combineCards.py", line 108, in <module>
    r = str(errline[b][p]);
TypeError: list indices must be integers, not str

the reason is for this kind of line, errline will be translate to a list instead of a dictionary of dictionaries.

With this commit we catch the TypeError which is raised in these cases and print a menaningful error message:

Traceback (most recent call last):
  File "/work/gallim/CMSSW/CMSSW_11_2_0_pre10/bin/slc7_amd64_gcc900/combineCards.py", line 115, in <module>
    raise NotImplementedError(error_message)
NotImplementedError: You probably have a regularization term in datacard Analyses/hig-19-002/ptH/fullmodel.txt.
A constraint term is a line that looks like the following:

        constr0 constr @3*(@0-2*@1+@2) r_0,r_1,r_2,regularize[0.] delta[10.]

Remove it and try again